version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
  webserver:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
  postgres:
    image: kartoza/postgis
    volumes:
      - ./postgres/travel.sql:/docker-entrypoint-initdb.d/travel.sql
    env_file:
      - ./postgres/database.env
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm start'
